### ISSUE TITLE
Still available ?

### ISSUE THREAD

**Issue by whoo** [aidanhs/zenrox#1]
Hi,

The API seems to be incomplete ... so I tried your software.
But I've got some issue with:

```python
Traceback (most recent call last):
  File "zenrox.py", line 477, in <module>
    main()
  File "zenrox.py", line 464, in main
    sys.exit(curses.wrapper(action_curses))
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "zenrox.py", line 319, in action_curses
    userid, auth, mobauth = initapi()
  File "zenrox.py", line 219, in initapi
    assert resp.status_code == 200
```

If there is a workaround.

**Comment by aidanhs** [comment]
I (happily!) no longer need to use tenrox - so unfortunately you'll probably need to dig into it yourself.

My starting point was to reverse engineer the mobile application, which was a bit of a pain - I added an SSL root certificate to my phone, and then intercepted all traffic and decrypted it in order to figure out what API calls the mobile app uses.

Good luck!

**Comment by aidanhs** [comment]
(the steps I took to intercept the mobile app are actually at https://github.com/aidanhs/zenrox/blob/master/tenrox_intercept - it may or may not work any more)
